### ISSUE TITLE
Comment faire quand le certificat arrive à péremption ?

### ISSUE THREAD

**Issue by memento** [Merrick28/seedbox-docker#4]
Bonjour,

Merci de votre travail !
Comment faire quand le certificat arrive à péremption ?
Quelle est la façon la plus propre et respectueuse du projet pour mettre à jour le certificat let's encrypt ?

Bien à vous.
Bonne journée !

**Comment by Merrick28** [comment]
Bonjour,

c'est traefik qui s'occupe de ça tout seul, il n'y a rien à gérer. Il suffit de laisser tourner, dès qu'il arrivera proche de l'expiration, il demander à letsencrypt d'en générer un nouveau :)

**Comment by memento** [comment]
Bonsoir,

Le certificat est pourtant arrivé à expiration il y a 5 jours et malgré un seedbox.sh (--)restart, rien n'y fait. Le restart a bien lieu mais pas le renouvellement du certificat qui reste périmé. Puis-je lancer une tâche manuellement pour le "forcer" à vérifier le certificat et le renouveler ?

--restart : 
```
./seedbox.sh --restart

Stopping seedboxdocker_sickrage_alexandre_1    ... done
Stopping seedboxdocker_couchpotato_alexandre_1 ... done
Stopping seedboxdocker_rutorrent-alexandre_1   ... done
Stopping pure_ftp_seedbox                      ... done
Stopping seedboxdocker_postfix_1               ... done
Stopping seedboxdocker_portainer_1             ... done
Stopping seedboxdocker_traefik_1               ... done
Removing seedboxdocker_sickrage_alexandre_1    ... done
Removing seedboxdocker_couchpotato_alexandre_1 ... done
Removing seedboxdocker_rutorrent-alexandre_1   ... done
Removing pure_ftp_seedbox                      ... done
Removing seedboxdocker_postfix_1               ... done
Removing seedboxdocker_portainer_1             ... done
Removing seedboxdocker_traefik_1               ... done
Removing network seedboxdocker_default
Creating network "seedboxdocker_default" with the default driver
Creating seedboxdocker_postfix_1 ... 
Creating pure_ftp_seedbox ... 
Creating seedboxdocker_traefik_1 ... 
Creating seedboxdocker_portainer_1 ... 
Creating seedboxdocker_rutorrent-alexandre_1 ... 
Creating pure_ftp_seedbox
Creating seedboxdocker_postfix_1
Creating seedboxdocker_traefik_1
Creating seedboxdocker_rutorrent-alexandre_1
Creating seedboxdocker_rutorrent-alexandre_1 ... done
Creating seedboxdocker_couchpotato_alexandre_1 ... 
Creating seedboxdocker_sickrage_alexandre_1 ... 
Creating seedboxdocker_couchpotato_alexandre_1
Creating seedboxdocker_sickrage_alexandre_1 ... done
```
restart : 
```
./seedbox.sh restart

seedboxdocker_postfix_1 is up-to-date
pure_ftp_seedbox is up-to-date
seedboxdocker_rutorrent-alexandre_1 is up-to-date
seedboxdocker_traefik_1 is up-to-date
seedboxdocker_portainer_1 is up-to-date
seedboxdocker_couchpotato_alexandre_1 is up-to-date
seedboxdocker_sickrage_alexandre_1 is up-to-date
```


Merci d'avance !

**Comment by memento** [comment]
Y-a-t-il un répertoire particulier où trouver les logs ?

**Comment by memento** [comment]
Dans le docker-compose.yml, j'ai une mention de :
```
###################################
#    TRAEFIK
###################################
  traefik:
    image: traefik:latest
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --entryPoints='Name:https Address::443 TLS' --entryPoints='Name:http Address::80  Redirect.EntryPoint:https' --acme.entrypoint=https -$
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - $CONFIG_DIR/traefik:/etc/traefik/acme
      - $CONFIG_DIR/certs:/certs
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:${ADMIN_URL}"
      - "traefik.backend.port=8080"
      - "traefik.frontend.auth.basic=admin:${passwd_admin}"
      - "traefik.frontend.entryPoints=https,http"
```

Or, [ici](https://github.com/Merrick28/seedbox-docker/commit/f266e0e0bac0fddd6f7b927536d5491f79099108), j'ai vu que vous aviez commité en passant la version de "latest" à "v1.5.0-rc5", ainsi que l'ajout du paramètre : 
```
--acme.httpchallenge.entrypoint=http
```
à la commande "command".
Je pense qu'i faudrait que je mette à jour le repo, qu'en pensez-vous ?
